name: ci

on:
  push:
    branches: [master, beta]
  pull_request:
    branches: [master, beta]

permissions:
  contents: read

jobs:
  build_and_lint:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    env:
      # octokit tries to use GITHUB_TOKEN opportunistically, so providing the token should increase our rate limits
      GITHUB_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - run: npm ci
      - run: npm run build

      - run: npm run lint:commit -- --to "${{ github.sha }}"
        if: ${{ runner.os == 'Linux' }}

      - run: npm run lint:typescript
        if: ${{ runner.os == 'Linux' }}

      - run: npm run lint:eslint
        if: ${{ runner.os == 'Linux' }}

      - run: npm run lint:prettier
        if: ${{ runner.os == 'Linux' }}

      - run: npm run test
      - run: npm run start
