name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - run: npm ci
      - run: npm run build
      - run: npm run lint:commit -- --to "${{ github.sha }}"
      - run: npm run lint:eslint
      - run: npm run lint:prettier
      - run: npm run test
      - run: npm run start
